workflows:
  ios-build:
    name: iOS Build with Firebase Fix
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Clean and patch Podfile
        script: |
          rm -rf ios/Pods ios/Podfile.lock
          if grep -q "use_modular_headers!" ios/Podfile; then
            echo "Patching Podfile..."
            sed -i '' "/use_modular_headers!/a\\
            pod 'Firebase/Messaging', :modular_headers => true
            " ios/Podfile
          fi
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install
          cd ..
      - name: Build iOS
        script: |
          flutter build ios --release
