workflows:
  ios-build:
    name: iOS Build with Firebase Modular Headers Fix
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: 🔄 Clean Flutter & Get Packages
        script: |
          flutter clean
          flutter pub get

      - name: 🧹 Clean DerivedData & Reinstall Pods
        script: |
          rm -rf ~/Library/Developer/Xcode/DerivedData
          cd ios
          pod deintegrate
          pod install --repo-update
          cd ..

      - name: ⚙️ Set Swift Flags for Firebase Interface Issues
        script: |
          export OTHER_SWIFT_FLAGS="-Xfrontend -disable-module-interface-validation"

      - name: 🛠️ Optional Header Patch (if needed)
        script: |
          if [ -f ios/Pods/Headers/Public/Firebase/Firebase.h ]; then
            echo "✅ Firebase.h found, archiving for inspection"
            zip -r firebase-headers.zip ios/Pods/Headers/Public/Firebase
          else
            echo "⚠️ Firebase.h not found - may not be generated yet"
          fi

      - name: 📦 Archive Podfile.lock
        script: |
          zip -j podfile-lock.zip ios/Podfile.lock

      - name: 🏗️ Build iOS IPA (no codesign)
        script: |
          flutter build ipa --release --no-codesign --no-tree-shake-icons --verbose

    artifacts:
      - build/ios/ipa/*.ipa
      - podfile-lock.zip
      - firebase-headers.zip

    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - $HOME/.pub-cache
        - ios/Pods

    publishing:
      email:
        recipients:
          - pravinshann02@gmail.com
