workflows:
  ios-build:
    name: iOS Build with Firebase Fixes
    environment:
      flutter: 3.32.6
      xcode: latest
      cocoapods: default

    scripts:
      - name: 🔄 Full Clean & Pod Reinstall
        script: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock ios/.symlinks
          rm -rf ios/Flutter/Flutter.framework ios/Flutter/engine
          rm -rf ~/Library/Developer/Xcode/DerivedData
          flutter pub get
          cd ios
          pod repo update                # ✅ <--- Add this line
          pod install --repo-update
          cd ..

      - name: 🔧 Patch Podfile for Firebase modular headers and SwiftEmit fix
        script: |
          sed -i '' 's/use_frameworks! .*/use_frameworks! :linkage => :static\n  use_modular_headers!/' ios/Podfile
          sed -i '' "s/pod 'FirebaseMessaging'/pod 'FirebaseMessaging', :modular_headers => true/" ios/Podfile
          sed -i '' "s/pod 'FirebaseDynamicLinks'/pod 'FirebaseDynamicLinks', :modular_headers => true/" ios/Podfile

      - name: 🧩 Reinstall CocoaPods
        script: |
          cd ios
          pod deintegrate
          pod install --repo-update
          cd ..

      - name: ⚙️ Add Swift Flags (optional fallback)
        script: |
          echo 'OTHER_SWIFT_FLAGS = -Xfrontend -disable-module-interface-validation' >> ios/Flutter/Debug.xcconfig
          echo 'OTHER_SWIFT_FLAGS = -Xfrontend -disable-module-interface-validation' >> ios/Flutter/Profile.xcconfig
          echo 'OTHER_SWIFT_FLAGS = -Xfrontend -disable-module-interface-validation' >> ios/Flutter/Release.xcconfig

      - name: 📦 Archive Podfile.lock
        script: |
          zip -j podfile-lock.zip ios/Podfile.lock

      - name: 🏗️ Build IPA (no code signing)
        script: |
          flutter build ipa --release --no-codesign --no-tree-shake-icons --verbose

    artifacts:
      - build/ios/ipa/*.ipa
      - podfile-lock.zip

    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - $HOME/.pub-cache
