workflows:
  ios-build:
    name: iOS Build with Firebase Dynamic Links Fix
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    environment:
      flutter: stable
      xcode: latest
    certificates:
      - certificate: "certificate.p12"
        password: "12345678"  # 🔐 Or use Encrypted(env(IOS_CERT_PASSWORD))
    provisioning_profiles:
      - bundle_id: "oasis.eshop.multivendor"
        profile: "Oasis_Cart_iOS_App_ios_app_store_1752145014.mobileprovision"
    scripts:
      - name: Clean Pod cache
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          cd ..
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install --repo-update
          cd ..
      - name: Build iOS
        script: |
          flutter build ios --release


