workflows:
  ios-build:
    name: iOS Build with Firebase Messaging Fix
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Clean Pod cache
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          cd ..
      - name: Patch Podfile with modular Firebase Messaging
        script: |
          if grep -q "use_modular_headers!" ios/Podfile; then
            echo "Patching Podfile for Firebase Messaging..."
            sed -i '' "/use_modular_headers!/a\\
            pod 'Firebase/Messaging', :modular_headers => true
            " ios/Podfile
          else
            echo "ERROR: use_modular_headers! not found in Podfile"
            exit 1
          fi
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install
          cd ..
      - name: Build iOS
        script: |
          flutter build ios --release
