workflows:
  ios-build:
    name: iOS Build with Firebase Modular Headers Fix
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: 🔄 Clean Flutter & Get Packages
        script: |
          flutter clean
          flutter pub get

      # 🧹 Full Cleanup: DerivedData, Pod Cache, Flutter Build Artifacts
      - script: |
          rm -rf ~/Library/Developer/Xcode/DerivedData
          rm -rf ios/Pods ios/.symlinks ios/Flutter/Flutter.framework ios/Flutter/App.framework ios/Flutter/engine .dart_tool build

      - name: 🧩 Reinstall Pods from Scratch
        script: |
          cd ios
          pod deintegrate
          pod install --repo-update
          cd ..

      - name: ⚙️ Patch OTHER_SWIFT_FLAGS into .xcconfig
        script: |
          echo "OTHER_SWIFT_FLAGS = -Xfrontend -disable-module-interface-validation" >> ios/Flutter/Release.xcconfig
          echo "OTHER_SWIFT_FLAGS = -Xfrontend -disable-module-interface-validation" >> ios/Flutter/Debug.xcconfig
          echo "OTHER_SWIFT_FLAGS = -Xfrontend -disable-module-interface-validation" >> ios/Flutter/Profile.xcconfig

      - name: 🛠️ Optional Firebase Header Patch
        script: |
          if [ -f ios/Pods/Headers/Public/Firebase/Firebase.h ]; then
            echo "✅ Firebase.h found, archiving for inspection"
            zip -r firebase-headers.zip ios/Pods/Headers/Public/Firebase
          fi

      - name: 📦 Archive Podfile.lock
        script: |
          zip -j podfile-lock.zip ios/Podfile.lock

      - name: 🏗️ Build iOS IPA (no codesign)
        script: |
          flutter build ipa --release --no-codesign --no-tree-shake-icons --verbose

    artifacts:
      - build/ios/ipa/*.ipa
      - podfile-lock.zip
      - firebase-headers.zip

    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - $HOME/.pub-cache
