workflows:
  ios-build:
    name: iOS Build with Firebase Dynamic Links Fix
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Clean Pod cache
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          cd ..


      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install --repo-update
          cd ..

      - name: Build iOS
        script: |
          flutter build ios --release
