workflows:
  ios-build:
    name: iOS Build with Firebase Modular Headers Fix
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: 🔄 Clean Flutter & Get Packages
        script: |
          flutter clean
          flutter pub get

      - name: 🧹 Clean DerivedData & Reinstall Pods (Keep Pods folder)
        script: |
          rm -rf ~/Library/Developer/Xcode/DerivedData
          cd ios
          pod install --repo-update
          cd ..


      - name: 🐦 Generate pigeon files for wakelock_plus
        script: |
          pigeon \
          --input .pub-cache/hosted/pub.dev/wakelock_plus-1.3.2/pigeons/messages.dart \
          --objc_header_out .pub-cache/hosted/pub.dev/wakelock_plus-1.3.2/ios/wakelock_plus/Sources/wakelock_plus/messages.g.h \
          --objc_source_out .pub-cache/hosted/pub.dev/wakelock_plus-1.3.2/ios/wakelock_plus/Sources/wakelock_plus/messages.g.m \
          --dart_out .pub-cache/hosted/pub.dev/wakelock_plus-1.3.2/lib/messages.g.dart

      - name: 🛠️ Optional Header Patch (if needed)
        script: |
          if [ -f ios/Pods/Headers/Public/Firebase/Firebase.h ]; then
            echo "✅ Firebase.h found, archiving for inspection"
            zip -r firebase-headers.zip ios/Pods/Headers/Public/Firebase
          else
            echo "⚠️ Firebase.h not found - may not be generated yet"
          fi

      - name: 📦 Archive Podfile.lock
        script: |
          zip -j podfile-lock.zip ios/Podfile.lock

      - name: 🏗️ Build iOS IPA (no codesign)
        script: |
          flutter build ipa --release --no-codesign 

    artifacts:
      - build/ios/ipa/*.ipa
      - podfile-lock.zip
      - firebase-headers.zip

    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - $HOME/.pub-cache
        - ios/Pods

    publishing:
      email:
        recipients:
          - pravinshann02@gmail.com
