workflows:
  ios-build:
    name: iOS Build with Firebase Dynamic Links Fix
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Clean Pod cache
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          cd ..

      - name: Fully patch Podfile with modular headers and post_install
        script: |
          echo "Patching Podfile for modular headers and non-modular includes..."

          # Ensure use_frameworks! and use_modular_headers!
          sed -i '' 's/^use_frameworks!/use_frameworks!\nuse_modular_headers!/' ios/Podfile

          # Add modular_headers for Firebase/Core and Messaging
          echo "pod 'Firebase/Core', :modular_headers => true" >> ios/Podfile
          echo "pod 'Firebase/Messaging', :modular_headers => true" >> ios/Podfile

          # Append post_install block safely
          echo "" >> ios/Podfile
          echo "post_install do |installer|" >> ios/Podfile
          echo "  installer.pods_project.targets.each do |target|" >> ios/Podfile
          echo "    target.build_configurations.each do |config|" >> ios/Podfile
          echo "      config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'" >> ios/Podfile
          echo "    end" >> ios/Podfile
          echo "  end" >> ios/Podfile
          echo "end" >> ios/Podfile

      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install --repo-update
          cd ..

      - name: Build iOS
        script: |
          flutter build ios --release
