workflows:
  ios-build:
    name: iOS Build with Firebase Patch
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: 🔄 Clean Flutter build & get dependencies
        script: |
          flutter clean
          flutter pub get

      - name: 🧹 Clean CocoaPods + Derived Data Cache
        script: |
          rm -rf ~/Library/Caches/CocoaPods
          rm -rf ~/Library/Developer/Xcode/DerivedData
          cd ios
          rm -rf Pods Podfile.lock
          pod install --repo-update
          cd ..

      - name: 🏗️ Build iOS IPA (no codesign)
        script: |
          flutter build ipa --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa

    # Optional but recommended for debugging
    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - $HOME/.pub-cache
        - ios/Pods

    publishing:
      email:
        recipients:
          - pravinshann02@gmail.com
