workflows:
  ios-build:
    name: iOS Build with Firebase Dynamic Links Fix
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Clean Pod cache
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          cd ..
      - name: Patch Podfile with modular Firebase Messaging
        script: |
          if grep -q "use_modular_headers!" ios/Podfile; then
            echo "Patching Podfile for Firebase Messaging..."
            sed -i '' "/use_modular_headers!/a\\
            pod 'Firebase/Messaging', :modular_headers => true
            " ios/Podfile
          else
            echo "ERROR: use_modular_headers! not found in Podfile"
            exit 1
          fi
      - name: Add post_install hook for non-modular includes
        script: |
          echo "Patching Podfile to allow non-modular includes..."
          cat <<EOF >> ios/Podfile

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    end
  end
end
EOF
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install
          cd ..
      - name: Build iOS
        script: |
          flutter build ios --release
