// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFyARTe5htvFenm-AwoVUOES3iwce8sjM',
    appId: '1:327324836622:web:252e7906b04fde8136ad5f',
    messagingSenderId: '327324836622',
    projectId: 'eshop-multivendor-new',
    authDomain: 'eshop-multivendor-new.firebaseapp.com',
    storageBucket: 'eshop-multivendor-new.appspot.com',
    measurementId: 'G-J7Y3R8EJPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByRDuOD33iwiGkwcq2t81tFte2fb6Meqk',
    appId: '1:853516694037:android:bbaa285882b09dff75541c',
    messagingSenderId: '853516694037',
    projectId: 'oasiscart-cc4c1',
    storageBucket: 'oasiscart-cc4c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2g8Sh8UuUT6gH9KZQ7G-QgJNCMYAyjnE',
    appId: '1:853516694037:ios:1fcb9c142bd88b2f75541c',
    messagingSenderId: '853516694037',
    projectId: 'oasiscart-cc4c1',
    storageBucket: 'oasiscart-cc4c1.firebasestorage.app',
    androidClientId: '853516694037-1a85gstju8mamff4mg615e4tdcgacmg0.apps.googleusercontent.com',
    iosClientId: '853516694037-18liki5309jnmfmubuc5jnklf8l0ml59.apps.googleusercontent.com',
    iosBundleId: 'oasis.eshop.multivendor',
  );

}